name: Fetch Satellites Every 30 Seconds

on:
  workflow_dispatch:  # 👈 allows manual trigger
  schedule:
    - cron: "*/5 * * * *"  # GitHub only allows min every 5 mins

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Backend/requirements.txt

      - name: Run satellite fetch script
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          N2YO_API_KEY: ${{ secrets.N2YO_API_KEY }}
        run: |
          Backend/utils/fetch_satellites.py
