name: Fetch Satellites Every 5 Minutes

on:
  workflow_dispatch:  # Allows manual trigger
  schedule:
    - cron: "*/5 * * * *"  # GitHub allows min every 5 minutes

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Backend/requirements.txt

      - name: Grant execute permissions to the fetch_satellites.py script
        run: chmod +x Backend/utils/fetch_satellites.py  # Make the script executable
        
      - name: Debug file permissions
        run: ls -l Backend/utils
        
      - name: Run satellite fetch script
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          N2YO_API_KEY: ${{ secrets.N2YO_API_KEY }}
        run: |
          python3 Backend/utils/fetch_satellites.py  # Ensure script is run with Python
